// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/pubsubjs/pubsub.d.ts
declare namespace PubSubJS {
    interface Base extends Publish, Subscribe, Unsubscribe, ClearAllSubscriptions {
        version: string;
        name: string;
    }

    interface Publish{
        publish(message: any, data: any): boolean;

        publish(message:any, data:any, sync:boolean, immediateExceptions:Function): boolean;

        publishSync(message: any, data: any): boolean;
    }

    interface Subscribe{
        subscribe(message: any, func: Function): any;
    }


    interface Unsubscribe{
        unsubscribe(tokenOrFunction: any): any;
    }


    interface ClearAllSubscriptions{
        clearAllSubscriptions(): any;
    }
}

declare var PubSub: PubSubJS.Base;

declare module "pubsub-js" {
  export = PubSub;
}
